package com.one.tomato.thirdpart.emotion;

import com.broccoli.p150bh.R;
import java.util.LinkedHashMap;

/* loaded from: classes3.dex */
public class EmotionArray {
    public static final String[] page_1 = {"[a_1]", "[a_2]", "[a_3]", "[a_4]", "[a_5]", "[a_6]", "[a_7]", "[a_8]", "[a_9]", "[a_10]", "[a_11]", "[a_12]", "[a_13]", "[a_14]", "[a_15]", "[a_16]", "[a_17]", "[a_18]", "[a_19]", "[a_20]", "[a_21]", "[a_22]", "[a_23]", "[a_24]", "[a_25]", "[a_26]", "[a_27]"};
    public static final String[] page_2 = {"[b_1]", "[b_2]", "[b_3]", "[b_4]", "[b_5]", "[b_6]", "[b_7]", "[b_8]", "[b_9]", "[b_10]", "[b_11]", "[b_12]", "[b_13]", "[b_14]", "[b_15]", "[b_16]", "[b_17]", "[b_18]", "[b_19]", "[b_20]", "[b_21]", "[b_22]", "[b_23]", "[b_24]", "[b_25]", "[b_26]", "[b_27]"};
    public static final String[] page_3 = {"[c_1]", "[c_2]", "[c_3]", "[c_4]", "[c_5]", "[c_6]", "[c_7]", "[c_8]", "[c_9]", "[c_10]", "[c_11]", "[c_12]", "[c_13]", "[c_14]", "[c_15]", "[c_16]", "[c_17]", "[c_18]", "[c_19]", "[c_20]", "[c_21]", "[c_22]", "[c_23]", "[c_24]", "[c_25]", "[c_26]", "[c_27]", "[c_28]", "[c_29]", "[c_30]", "[c_31]"};
    public static final String[] page_4 = {"[d_1]", "[d_2]", "[d_3]", "[d_4]", "[d_5]", "[d_6]", "[d_7]", "[d_8]", "[d_9]", "[d_10]", "[d_11]", "[d_12]", "[d_13]", "[d_14]", "[d_15]", "[d_16]", "[d_17]", "[d_18]", "[d_19]", "[d_20]", "[d_21]", "[d_22]", "[d_23]", "[d_24]", "[d_25]", "[d_26]", "[d_27]"};
    public static LinkedHashMap<String, Integer> pageMap1 = new LinkedHashMap<>();
    public static LinkedHashMap<String, Integer> pageMap2 = new LinkedHashMap<>();
    public static LinkedHashMap<String, Integer> pageMap3 = new LinkedHashMap<>();
    public static LinkedHashMap<String, Integer> pageMap4 = new LinkedHashMap<>();
    public static LinkedHashMap<String, Integer> allPageMap = new LinkedHashMap<>();

    static {
        pageMap1.put(page_1[0], Integer.valueOf((int) R.drawable.a_1));
        pageMap1.put(page_1[1], Integer.valueOf((int) R.drawable.a_2));
        pageMap1.put(page_1[2], Integer.valueOf((int) R.drawable.a_3));
        pageMap1.put(page_1[3], Integer.valueOf((int) R.drawable.a_4));
        pageMap1.put(page_1[4], Integer.valueOf((int) R.drawable.a_5));
        pageMap1.put(page_1[5], Integer.valueOf((int) R.drawable.a_6));
        pageMap1.put(page_1[6], Integer.valueOf((int) R.drawable.a_7));
        pageMap1.put(page_1[7], Integer.valueOf((int) R.drawable.a_8));
        pageMap1.put(page_1[8], Integer.valueOf((int) R.drawable.a_9));
        pageMap1.put(page_1[9], Integer.valueOf((int) R.drawable.a_10));
        pageMap1.put(page_1[10], Integer.valueOf((int) R.drawable.a_11));
        pageMap1.put(page_1[11], Integer.valueOf((int) R.drawable.a_12));
        pageMap1.put(page_1[12], Integer.valueOf((int) R.drawable.a_13));
        pageMap1.put(page_1[13], Integer.valueOf((int) R.drawable.a_14));
        pageMap1.put(page_1[14], Integer.valueOf((int) R.drawable.a_15));
        pageMap1.put(page_1[15], Integer.valueOf((int) R.drawable.a_16));
        pageMap1.put(page_1[16], Integer.valueOf((int) R.drawable.a_17));
        pageMap1.put(page_1[17], Integer.valueOf((int) R.drawable.a_18));
        pageMap1.put(page_1[18], Integer.valueOf((int) R.drawable.a_19));
        pageMap1.put(page_1[19], Integer.valueOf((int) R.drawable.a_20));
        pageMap1.put(page_1[20], Integer.valueOf((int) R.drawable.a_21));
        pageMap1.put(page_1[21], Integer.valueOf((int) R.drawable.a_22));
        pageMap1.put(page_1[22], Integer.valueOf((int) R.drawable.a_23));
        pageMap1.put(page_1[23], Integer.valueOf((int) R.drawable.a_24));
        pageMap1.put(page_1[24], Integer.valueOf((int) R.drawable.a_25));
        pageMap1.put(page_1[25], Integer.valueOf((int) R.drawable.a_26));
        pageMap1.put(page_1[26], Integer.valueOf((int) R.drawable.a_27));
        pageMap2.put(page_2[0], Integer.valueOf((int) R.drawable.b_1));
        pageMap2.put(page_2[1], Integer.valueOf((int) R.drawable.b_2));
        pageMap2.put(page_2[2], Integer.valueOf((int) R.drawable.b_3));
        pageMap2.put(page_2[3], Integer.valueOf((int) R.drawable.b_4));
        pageMap2.put(page_2[4], Integer.valueOf((int) R.drawable.b_5));
        pageMap2.put(page_2[5], Integer.valueOf((int) R.drawable.b_6));
        pageMap2.put(page_2[6], Integer.valueOf((int) R.drawable.b_7));
        pageMap2.put(page_2[7], Integer.valueOf((int) R.drawable.b_8));
        pageMap2.put(page_2[8], Integer.valueOf((int) R.drawable.b_9));
        pageMap2.put(page_2[9], Integer.valueOf((int) R.drawable.b_10));
        pageMap2.put(page_2[10], Integer.valueOf((int) R.drawable.b_11));
        pageMap2.put(page_2[11], Integer.valueOf((int) R.drawable.b_12));
        pageMap2.put(page_2[12], Integer.valueOf((int) R.drawable.b_13));
        pageMap2.put(page_2[13], Integer.valueOf((int) R.drawable.b_14));
        pageMap2.put(page_2[14], Integer.valueOf((int) R.drawable.b_15));
        pageMap2.put(page_2[15], Integer.valueOf((int) R.drawable.b_16));
        pageMap2.put(page_2[16], Integer.valueOf((int) R.drawable.b_17));
        pageMap2.put(page_2[17], Integer.valueOf((int) R.drawable.b_18));
        pageMap2.put(page_2[18], Integer.valueOf((int) R.drawable.b_19));
        pageMap2.put(page_2[19], Integer.valueOf((int) R.drawable.b_20));
        pageMap2.put(page_2[20], Integer.valueOf((int) R.drawable.b_21));
        pageMap2.put(page_2[21], Integer.valueOf((int) R.drawable.b_22));
        pageMap2.put(page_2[22], Integer.valueOf((int) R.drawable.b_23));
        pageMap2.put(page_2[23], Integer.valueOf((int) R.drawable.b_24));
        pageMap2.put(page_2[24], Integer.valueOf((int) R.drawable.b_25));
        pageMap2.put(page_2[25], Integer.valueOf((int) R.drawable.b_26));
        pageMap2.put(page_2[26], Integer.valueOf((int) R.drawable.b_27));
        pageMap3.put(page_3[0], Integer.valueOf((int) R.drawable.c_1));
        pageMap3.put(page_3[1], Integer.valueOf((int) R.drawable.c_2));
        pageMap3.put(page_3[2], Integer.valueOf((int) R.drawable.c_3));
        pageMap3.put(page_3[3], Integer.valueOf((int) R.drawable.c_4));
        pageMap3.put(page_3[4], Integer.valueOf((int) R.drawable.c_5));
        pageMap3.put(page_3[5], Integer.valueOf((int) R.drawable.c_6));
        pageMap3.put(page_3[6], Integer.valueOf((int) R.drawable.c_7));
        pageMap3.put(page_3[7], Integer.valueOf((int) R.drawable.c_8));
        pageMap3.put(page_3[8], Integer.valueOf((int) R.drawable.c_9));
        pageMap3.put(page_3[9], Integer.valueOf((int) R.drawable.c_10));
        pageMap3.put(page_3[10], Integer.valueOf((int) R.drawable.c_11));
        pageMap3.put(page_3[11], Integer.valueOf((int) R.drawable.c_12));
        pageMap3.put(page_3[12], Integer.valueOf((int) R.drawable.c_13));
        pageMap3.put(page_3[13], Integer.valueOf((int) R.drawable.c_14));
        pageMap3.put(page_3[14], Integer.valueOf((int) R.drawable.c_15));
        pageMap3.put(page_3[15], Integer.valueOf((int) R.drawable.c_16));
        pageMap3.put(page_3[16], Integer.valueOf((int) R.drawable.c_17));
        pageMap3.put(page_3[17], Integer.valueOf((int) R.drawable.c_18));
        pageMap3.put(page_3[18], Integer.valueOf((int) R.drawable.c_19));
        pageMap3.put(page_3[19], Integer.valueOf((int) R.drawable.c_20));
        pageMap3.put(page_3[20], Integer.valueOf((int) R.drawable.c_21));
        pageMap3.put(page_3[21], Integer.valueOf((int) R.drawable.c_22));
        pageMap3.put(page_3[22], Integer.valueOf((int) R.drawable.c_23));
        pageMap3.put(page_3[23], Integer.valueOf((int) R.drawable.c_24));
        pageMap3.put(page_3[24], Integer.valueOf((int) R.drawable.c_25));
        pageMap3.put(page_3[25], Integer.valueOf((int) R.drawable.c_26));
        pageMap3.put(page_3[26], Integer.valueOf((int) R.drawable.c_27));
        pageMap3.put(page_3[27], Integer.valueOf((int) R.drawable.c_28));
        pageMap3.put(page_3[28], Integer.valueOf((int) R.drawable.c_29));
        pageMap3.put(page_3[29], Integer.valueOf((int) R.drawable.c_30));
        pageMap3.put(page_3[30], Integer.valueOf((int) R.drawable.c_31));
        pageMap4.put(page_4[0], Integer.valueOf((int) R.drawable.d_1));
        pageMap4.put(page_4[1], Integer.valueOf((int) R.drawable.d_2));
        pageMap4.put(page_4[2], Integer.valueOf((int) R.drawable.d_3));
        pageMap4.put(page_4[3], Integer.valueOf((int) R.drawable.d_4));
        pageMap4.put(page_4[4], Integer.valueOf((int) R.drawable.d_5));
        pageMap4.put(page_4[5], Integer.valueOf((int) R.drawable.d_6));
        pageMap4.put(page_4[6], Integer.valueOf((int) R.drawable.d_7));
        pageMap4.put(page_4[7], Integer.valueOf((int) R.drawable.d_8));
        pageMap4.put(page_4[8], Integer.valueOf((int) R.drawable.d_9));
        pageMap4.put(page_4[9], Integer.valueOf((int) R.drawable.d_10));
        pageMap4.put(page_4[10], Integer.valueOf((int) R.drawable.d_11));
        pageMap4.put(page_4[11], Integer.valueOf((int) R.drawable.d_12));
        pageMap4.put(page_4[12], Integer.valueOf((int) R.drawable.d_13));
        pageMap4.put(page_4[13], Integer.valueOf((int) R.drawable.d_14));
        pageMap4.put(page_4[14], Integer.valueOf((int) R.drawable.d_15));
        pageMap4.put(page_4[15], Integer.valueOf((int) R.drawable.d_16));
        pageMap4.put(page_4[16], Integer.valueOf((int) R.drawable.d_17));
        pageMap4.put(page_4[17], Integer.valueOf((int) R.drawable.d_18));
        pageMap4.put(page_4[18], Integer.valueOf((int) R.drawable.d_19));
        pageMap4.put(page_4[19], Integer.valueOf((int) R.drawable.d_20));
        pageMap4.put(page_4[20], Integer.valueOf((int) R.drawable.d_21));
        pageMap4.put(page_4[21], Integer.valueOf((int) R.drawable.d_22));
        pageMap4.put(page_4[22], Integer.valueOf((int) R.drawable.d_23));
        pageMap4.put(page_4[23], Integer.valueOf((int) R.drawable.d_24));
        pageMap4.put(page_4[24], Integer.valueOf((int) R.drawable.d_25));
        pageMap4.put(page_4[25], Integer.valueOf((int) R.drawable.d_26));
        pageMap4.put(page_4[26], Integer.valueOf((int) R.drawable.d_27));
        allPageMap.putAll(pageMap1);
        allPageMap.putAll(pageMap2);
        allPageMap.putAll(pageMap3);
        allPageMap.putAll(pageMap4);
    }
}
